language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"


# command to install dependencies
install:
#  - pip install your_package
  - pip install metaframe

# command to run tests
script: cd tests && PYTHONPATH=.. nosetests -v -v
